@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
actor Client
participant "individuals-api"
participant "person-service"
participant Keycloak
participant "PS DB"


Client -> "individuals-api" : POST /registration
"individuals-api" -> "person-service" : POST /individuals
"person-service" -> "PS DB" : SAVE
"PS DB" --> "person-service" : OK
"person-service" --> "individuals-api" : uuid new user
"individuals-api" -> Keycloak : create user with uuid

alt OK Flow
  Keycloak --> "individuals-api" : OK
  "individuals-api" --> Keycloak : login
  Keycloak --> "individuals-api" : Tokens
  "individuals-api" --> Client : Tokens

else Not OK Flow
  Keycloak --> "individuals-api" : failed
  "individuals-api" -> "person-service" : DELETE /individuals/compensate-registration/{id}
  "person-service" -> "PS DB" : DELETE
  "PS DB" --> "person-service" : OK
  "person-service" --> "individuals-api" : OK
  "individuals-api" --> Client : failed
end
@enduml