global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['individuals-api:8081']
  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: [ 'keycloak:8080' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]