global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['individuals-api:8081'] #port depends on environment