openapi: 3.0.0
info:
  title: Person service API
  description: REST API для регистрации, получения пользователя по ID и email, обновление данных пользователя, удаление пользователя во внутренней системе.
  version: 1.0.0
servers:
  - url: http://localhost:8082

tags:
  - name: Person

paths:
  /v1/individuals:
    post:
      summary: Регистрация пользователя во внутренней системе
      operationId: "registration"
      security:
        - bearerAuth: [ ]
      tags:
        - Person
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer {token}"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndividualDto'
      responses:
        '201':
          description: Успешная регистрация, айди записи
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Пользователь уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Получение пользователя по Id и email
      operationId: "getIndividualById"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Id пользователя
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
          description: Email пользователя
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer {token}"
      tags:
        - Person
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualDto'
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/individuals/{id}:
    put:
      summary: Обновление пользователя
      operationId: "updateIndividualById"
      security:
        - bearerAuth: [ ]
      tags:
        - Person
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Id пользователя
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer {token}"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDto'
      responses:
        '200':
          description: Пользователь обновлен
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Удаление пользователя
      operationId: "deleteIndividual"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Id пользователя
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer {token}"
      tags:
        - Person
      responses:
        '200':
          description: Пользователь удален
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/individuals/compensate-registration/{id}:
    delete:
      summary: Компенсация транзакции по регистрации в случае неудачи
      operationId: "compensateFailedRegistration"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Id пользователя
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer {token}"
      tags:
        - Person
      responses:
        '200':
          description: Пользователь удален

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    IndividualDto:
      type: object
      required: [ passport_number, phone_number, status, email, first_name, last_name, address, zip_code, city, state, name, alpha2, alpha3 ]
      properties:
        passport_number:
          type: string
        phone_number:
          type: string
        user_status:
          type: string
        secret_key:
          type: string
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        filled:
          type: boolean
        address:
          type: string
        zip_code:
          type: string
        city:
          type: string
        state:
          type: string
        name:
          type: string
        alpha2:
          type: string
          maxLength: 2
        alpha3:
          type: string
          maxLength: 3
        status:
          type: string

    UpdateDto:
      type: object
      properties:
        passport_number:
          type: string
        phone_number:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        address:
          type: string
        zip_code:
          type: string
        city:
          type: string
        state:
          type: string
        name:
          type: string
        alpha2:
          type: string
          maxLength: 2
        alpha3:
          type: string
          maxLength: 3

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        status:
          type: integer

    RegistrationResponse:
      type: object
      properties:
        user_uid:
          type: string